TenderAssist/Controllers/GlobalTendersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using TenderAssist.CommonHelper;
using TenderAssist.Models;
using TenderAssist.ViewModel;
using static TenderAssist.CommonHelper.Utility;
using static TenderAssist.Models.SearchModel;

namespace TenderAssist.Controllers
{
    public class GlobalTendersController : BaseController
    {
        public GlobalTendersController()
        {
            _tenderInfo = new TenderInformation();
            _common = new CommonController();
            _getListItems = new GetListItems();
        }


        #region VARIABLES
        private readonly TenderInformation _tenderInfo;
        private readonly CommonController _common;
        private readonly GetListItems _getListItems;
        private static int PageSize = Convert.ToInt32(ConfigurationManager.AppSettings["DataPageSize"]);
        private List<string> WithinSearchWords = new List<string>();
        #endregion

        #region GLOBAL TENDER LIST PAGE

        public ActionResult Tenders()
        {
            return View(new TenderDetail()
            {
                IsAdvanceSearch = false,
                TendersBy = TenderTypeList.Keyword,
                CountryList = _getListItems.CountryList(),
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                IdVal = 0,
                Subscribetype = SubscribType.DownloadTender,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.DownloadTender,
                FormType = FormType.PopupForms,
                IsHomePage = true,
                IsGlobalTender = true
            });
        }
        public ActionResult Index(string keyword = "", string withinSearchText = "")
        {
            ResetTotalCountSession_Global();
            TenderDetail tenderDetail;

            int id = 0; int page = 0;
            const int tenderBy = TenderTypeList.SearchTender;
            var isSearchTextChanged = CheckWithinSearch(withinSearchText);

            var productlist = _tenderInfo.GetExactProduct(keyword.Trim());
            if (productlist.Any()) { id = productlist.FirstOrDefault().ProductsId; }

            var fieldId = id;
            var fieldName = keyword;
            //string countryIds = "";
            //int tenderStatusFlag = 0;

            if (Session["SearhGlobalTenderResult"] != null)
            {
                tenderDetail = (TenderDetail)Session["SearhGlobalTenderResult"];
                //countryIds = tenderDetail.SelectedCountry;
                //tenderStatusFlag = tenderDetail.TenderStatusFlag;

                var oldFieldId = tenderDetail.FieldId;
                if (oldFieldId != fieldId)
                {
                    isSearchTextChanged = true;
                }
            }
            var advanceSearchPara = SetDefaultAdvSearchParam();

            tenderDetail = GetTenderResult(tenderBy, page, "SearhGlobalTenderResult", advanceSearchPara, id, true, isSearchTextChanged);

            SetTenderDetails(tenderBy, "", fieldId, fieldName, ref tenderDetail);

            return View("Index", tenderDetail);
        }
        public ActionResult GetDefaultGlobalTender(int tenderStatus = 1)
        {
            List<SearchTenaderInfoWithAllDetail> tenaderInfoWithDetail = new List<SearchTenaderInfoWithAllDetail>();
            AdvanceSearchParameter AdvanceSearch = new AdvanceSearchParameter()
            {
                TenderStatusFlag = tenderStatus
            };

            var tenderDetail = _common.GetSearchGlobalTenderResult(0, 0, "", 1, AdvanceSearch, 0, false);
            tenderDetail.IsGlobalTender = true;
            tenaderInfoWithDetail = tenderDetail.AllSearchTenaderInfoWithAllDetail;

            return PartialView(Url.Content("~/Views/GlobalTenders/_HomeTenderListPanel.cshtml"), tenderDetail);
        }

        #region ----------ALL REGION BASED TENDER LIST----------

        public ActionResult MiddleEastCountryTenders(string countryName = "", string withinSearchText = "")
        {
            return View("Index", CountryRegionTenderList(TenderTypeList.MiddleEastCountryRegion, countryName, withinSearchText));
        }
        public ActionResult EuropeanCountryTenders(string countryName = "", string withinSearchText = "")
        {
            return View("Index", CountryRegionTenderList(TenderTypeList.EuropeanCountryRegion, countryName, withinSearchText));
        }
        public ActionResult AfricanCountryTenders(string countryName = "", string withinSearchText = "")
        {
            return View("Index", CountryRegionTenderList(TenderTypeList.AfricanCountryRegion, countryName, withinSearchText));
        }
        public ActionResult AsianCountryTenders(string countryName = "", string withinSearchText = "")
        {
            return View("Index", CountryRegionTenderList(TenderTypeList.AsianCountryRegion, countryName, withinSearchText));
        }
        public ActionResult SAARCountryTenders(string countryName = "", string withinSearchText = "")
        {
            return View("Index", CountryRegionTenderList(TenderTypeList.SaarCountryRegion, countryName, withinSearchText));
        }
        public ActionResult AustraliaOceaniaCountryTenders(string countryName = "", string withinSearchText = "")
        {
            return View("Index", CountryRegionTenderList(TenderTypeList.AustraliaOceaniaCountryRegion, countryName, withinSearchText));
        }
        public ActionResult SouthAmericaCountryTenders(string countryName = "", string withinSearchText = "")
        {
            return View("Index", CountryRegionTenderList(TenderTypeList.SouthAmericaCountryRegion, countryName, withinSearchText));
        }
        public ActionResult NorthAmericaCountryTenders(string countryName = "", string withinSearchText = "")
        {
            return View("Index", CountryRegionTenderList(TenderTypeList.NorthAmericaCountryRegion, countryName, withinSearchText));
        }

        private TenderDetail CountryRegionTenderList(int regionId, string countryName, string withinSearchText)
        {
            string sessionKeyName = "";
            switch (regionId)
            {
                default://SEARCH                             
                    sessionKeyName = "SearhGlobalTenderResult";
                    break;
                case TenderTypeList.MiddleEastCountryRegion:
                    sessionKeyName = "SearhMiddleEastCountryTenderResult";
                    break;
                case TenderTypeList.EuropeanCountryRegion:
                    sessionKeyName = "SearhEuropeanCountryTenderResult";
                    break;
                case TenderTypeList.AfricanCountryRegion:
                    sessionKeyName = "SearhAfricanCountryTenderResult";
                    break;
                case TenderTypeList.AsianCountryRegion:
                    sessionKeyName = "SearhAsianCountryTenderResult";
                    break;
                case TenderTypeList.SaarCountryRegion:
                    sessionKeyName = "SearhSAARCountryTenderResult";
                    break;
                case TenderTypeList.AustraliaOceaniaCountryRegion:
                    sessionKeyName = "SearhAustraliaOceaniaCountryTenderResult";
                    break;
                case TenderTypeList.SouthAmericaCountryRegion:
                    sessionKeyName = "SearhSouthAmericaCountryTenderResult";
                    break;
                case TenderTypeList.NorthAmericaCountryRegion:
                    sessionKeyName = "SearhNorthAmericaCountryTenderResult";
                    break;

            }

            ResetTotalCountSession_Global();
            TenderDetail tenderDetail;
            int id = 0; int page = 0;

            //const int regionId = TenderTypeList.MiddleEastCountryRegion;

            countryName = countryName.Replace("-", " ").ToLower().Trim().ToString();
            var countryList = _tenderInfo.ListCountrybyRegion(regionId).Where(x => x.CountryName.ToLower().Trim().ToString().Equals(countryName));
            if (countryList.Any()) { id = countryList.FirstOrDefault().CountryId; }

            var fieldId = id;
            var fieldName = countryName;
            var countries = "";

            var isSearchTextChanged = CheckWithinSearch(withinSearchText);

            if (Session[sessionKeyName] != null)
            {
                tenderDetail = (TenderDetail)Session[sessionKeyName];
                countries = tenderDetail.SelectedCountry;

                var oldFieldId = tenderDetail.FieldId;
                if (oldFieldId != fieldId)
                {
                    isSearchTextChanged = true;
                    countries = countries == "" ? fieldId.ToString() : countries + "," + fieldId.ToString();
                }
            }
            else
            {
                SearchedWordsClear();
                countries = fieldId.ToString();
            }
            var advanceSearchPara = SetDefaultAdvSearchParam();
            advanceSearchPara.SelectedCountries = countries;
            tenderDetail = CountryRegionWiseSearch(fieldId, fieldName, "", page, regionId, advanceSearchPara, isSearchTextChanged);

            return tenderDetail;
        }
        #endregion

        #endregion

        #region GLOBAL REGION LISTS

        public ActionResult TendersByMiddleEastCountry()
        {
            return View("CountryLinkByRegions", CountryRegion(Utility.TenderTypeList.MiddleEastCountryRegion));
        }
        public ActionResult TendersByEuropeanCountry()
        {
            return View("CountryLinkByRegions", CountryRegion(Utility.TenderTypeList.EuropeanCountryRegion));

        }
        public ActionResult TendersByAfricanCountry()
        {

TenderAssist/Views/GlobalTenders/CountryLinkByRegions.cshtml
@model TenderAssist.ViewModel.TenderDetail
 



<div class="container_fullMiddle">
    <div class="breadcrumbgrid">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb" itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb">
                    <div class="CurrentDiv">
                        <a href="/" itemprop="url" style="text-decoration: none;">
                            <span itemprop="title">Home</span>
                        </a>
                    </div>
                    <div itemprop="child" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                        <div class="CurrentDiv">
                            <span class="seperator">›</span>
                        </div>
                        <div class="CurrentDiv">
                            <a href="@Url.Action("Tenders", "GlobalTenders")" itemprop="url" style="text-decoration: none;">
                                <span itemprop="title">Global Tenders</span>
                            </a>

                        </div>
                    </div>
                    <div itemprop="child" itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb">
                        <div class="CurrentDiv">
                            <span class="seperator">›</span>
                        </div>
                        <div class="CurrentDiv">
                            <span itemprop="title" class="text-bold">
                                @Model.FormTitle
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @Html.Partial("partialCountryByRegionList", Model)
        </div>

    </div>

</div>

TenderAssist/Views/GlobalTenders/Index.cshtml
@model TenderAssist.ViewModel.TenderDetail


<script type="text/javascript">
    var Total = parseInt('@Model.Total');
    var TotalLive = parseInt('@Model.TotalLive');
    var TotalFresh = parseInt('@Model.TotalFresh');
    var TotalClosed = parseInt('@Model.TotalClosed');
</script>

<div class="container_fullMiddle">

    <div class="row">
        <div class="col-md-12">
            @Html.Partial("Partial/partialBreadCrumbForGlobalTenderList", Model)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("~/Views/GlobalTenders/Partial/AdvanceSearchPanels/partialAdvanceSearch.cshtml")
        </div>
        <div class="col-md-8">
            <div class="well well-sm">
                <div id="categories">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="section_panel">
                                @Html.Partial("Search/partialSearchPanel")
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="lineseperatorOrange"></div>
                                    </div>
                                </div>

                                <div id="displayPanel" class="display_panel">
                                    @{
                                        var activeClassAll = Model.TenderStatus == 0 ? "active tabCatLinks" : "tabCatLinks";
                                        var activeFreshAll = Model.TenderStatus == 2 ? "active tabCatLinks" : "tabCatLinks";
                                        var activeLiveAll = Model.TenderStatus == 1 ? "active tabCatLinks" : "tabCatLinks";
                                        var activeArchiveAll = Model.TenderStatus == 3 ? "active tabCatLinks" : "tabCatLinks";
                                    }

                                    <div class="row">
                                        <div class="col-md-12">
                                            <ul class="nav nav-tabs">
                                                <li class="@activeClassAll" id="linkAllTenders">
                                                    <a class="pointercursor" onclick="ChangeTenderStatus('0');">
                                                        All
                                                        <span id="lblAll" class="tabCatLinksSpans">
                                                            @if (Model.TenderStatus == 0)
                                                            {
                                                                <small><b>(@Model.Total)</b></small>
                                                            }
                                                        </span>
                                                    </a>
                                                </li>
                                                <li class="@activeFreshAll" id="linkFreshTenders">
                                                    <a class="pointercursor" onclick="ChangeTenderStatus('2');">
                                                        Fresh
                                                        <span id="lblFresh" class="tabCatLinksSpans">
                                                            @if (Model.TenderStatus == 2)
                                                            {
                                                                <small><b>(@Model.TotalFresh)</b></small>
                                                            }
                                                        </span>
                                                    </a>
                                                </li>
                                                <li class="@activeLiveAll" id="linkLiveTenders">
                                                    <a class="pointercursor" onclick="ChangeTenderStatus('1');">
                                                        Live
                                                        <span id="lblLive" class="tabCatLinksSpans">
                                                            @if (Model.TenderStatus == 1)
                                                            {
                                                                <small>(@Model.TotalLive)</small>
                                                            }
                                                        </span>

                                                    </a>
                                                </li>
                                                <li class="@activeArchiveAll" id="linkArchiveTenders">
                                                    <a class="pointercursor" onclick="ChangeTenderStatus('3');">
                                                        Archive
                                                        <span id="lblArchive" class="tabCatLinksSpans">
                                                            @if (Model.TenderStatus == 3)
                                                            {
                                                                <small>(@Model.TotalClosed)</small>
                                                            }
                                                        </span>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="card cardpanel">
                                                @Html.Partial("Search/_WithinSearch")
                                                    <div>
                                                        @{
                                                            if (Session["WithinSearchGlobalTextList"] != null)
                                                            {
                                                                var withinKeywords = (List<string>)Session["WithinSearchGlobalTextList"];
                                                                <div class="row">
                                                                    <div class="col-md-12">
                                                                        @foreach (var keyword in withinKeywords)
                                                                        {
                                                                            <div class="withinselecteditems" onclick="RemoveGlobalWithinSearch('@keyword')">
                                                                                @keyword
                                                                                <i class="fa fa-trash-o"></i>
                                                                            </div>
                                                                        }
                                                                    </div>
                                                                </div>


                                                            }
                                                        }
                                                    </div>

                                                <div id="divTenderInfo">
                                                    @Html.Partial("Partial/partialSearchResultData")
                                                </div>
                                                <div id="loader" style="display:none;">
                                                    @Html.Partial("partialSpinnerLoadingView")
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row" id="divloadmore">
                                        <div class="col-md-12">
                                            <div class="pull-right">
                                                <button type="button" class="btn btn-default btn-lg" id="btnLoadMoreData">
                                                    <i class="fa fa-eye-slash"></i>
                                                    View More...
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            @Html.Partial("~/Views/Home/Sections/_HomeAdvertiesment.cshtml")
        </div>
    </div>

</div>


@Html.Hidden("hdnPageUrl", Model.PaggingUrl)

@Html.Partial("_partialInquiryForm", Model)

<script type="text/javascript">

    var CurrentPage = '@ViewBag.CurrentPage';
    var TotalPage = parseInt('@ViewBag.TotalPage');
    var PageSize = '@ViewBag.PageSize';
    var NewPage = (parseInt('@ViewBag.CurrentPage') + 1);

    console.log('TotalPage - ' + TotalPage);

</script>


<style>
    .dropdown {
        margin-bottom: 10px;
    }

        .dropdown .selectButton {
            width: 100%;
            text-align: left;
        }

    .dropdown-header {
        padding: 3px 10px !important;
        font-size: 15px;
    }

    .dropdown-menu > li > a {
        padding: 3px 10px !important;
    }

    .dropdown-menu-class {
        max-height: 250px;
        overflow-y: scroll;
        width: 100%;
    }

    .tabCatLinksSpans {
        float: right;
        margin: 0 2px;
        margin-top: -1px;
        /*color:#4b4b4b;*/
    }

    .cardpanel {
        padding: 5px;
    }

    .withinselecteditems {
        font-size: 14px !important;
        cursor: pointer;
        font-size: 12px;
        background-color: #e0e0e0;
        box-shadow: 0 2px 4px 0 hsla(0,0%,100%,.5);
        border-radius: 3px;
        margin: 0px;
        overflow: hidden;
        transition: background-color .1s;
        max-width: 200px;
        padding: 6px;
        display: inline-block;
    }

        .withinselecteditems:hover {
            font-weight: bold;
            text-decoration: line-through;
        }
</style>

TenderAssist/Views/GlobalTenders/Tenders.cshtml
@model TenderAssist.ViewModel.TenderDetail
@using TenderAssist.Controllers;

@{
    GlobalTendersController _global = new GlobalTendersController();
    var TotalDisplay = 5;
}
<div class="container_fullMiddle">
    <div class="breadcrumbgrid">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb" itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb">
                    <div class="CurrentDiv">
                        <a href="/" itemprop="url" style="text-decoration: none;">
                            <span itemprop="title">Home</span>
                        </a>
                    </div>
                    <div itemprop="child" itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb">
                        <div class="CurrentDiv">
                            <span class="seperator">›</span>
                        </div>
                        <div class="CurrentDiv">
                            <span itemprop="title" class="text-bold">
                                Global Tenders
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="well well-sm">
                <div id="categories">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="section_panel">
                                @Html.Partial("Search/partialSearchPanel")
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="lineseperatorOrange"></div>
                                    </div>
                                </div>
                                <div id="loader" style="display:none;">
                                    @Html.Partial("partialSpinnerLoadingView")
                                </div>
                                <div class="section_panel">
                                    <div id="displayPanel" class="display_panel">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">            
            @{
                var tenderDetail = new TenderAssist.ViewModel.TenderDetail
                {
                    CountryList= Model.CountryList,
                    StateList = Model.StateList,
                    CityList = Model.CityList,
                    Subscribetype = TenderAssist.CommonHelper.Utility.SubscribType.GlobalTender,
                    DownloadTenderRefNo = 0,
                    FormTitle = TenderAssist.CommonHelper.Utility.SubscribTypeDisplsyText.GlobalTender,
                    FormType = TenderAssist.CommonHelper.Utility.FormType.RegistrationForm
                };
                @Html.Partial("_partialInquiryForm", tenderDetail)
            }
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @{Model.TotalDisplay = TotalDisplay;}
            @Html.Partial("partialCountryByRegionList_Home", Model)
        </div>
    </div>
</div>

@Html.Partial("_partialInquiryForm", Model)

<script>
    var loadDataList = '@Url.Action("GetDefaultGlobalTender", "GlobalTenders")';
    var isHomePage = true;
</script>



@Scripts.Render("~/bundles/global-search-script")

TenderAssist/Views/GlobalTenders/_HomeTenderListPanel.cshtml
@model TenderAssist.ViewModel.TenderDetail

@*<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs">            
            <li class="tabCatLinks" id="linkLiveTenders">
                <a onclick="GetGlobalTenderList(1);" class="pointercursor">
                    Live
                </a>
            </li>
            <li class="active tabCatLinks" id="linkFreshTenders">
                <a onclick="GetGlobalTenderList(2);" class="pointercursor">
                    Fresh
                </a>
            </li>            
        </ul>
    </div>
</div>*@
<div class="row">
    <div class="col-md-12">
        <div id="divTenderInfo">
            @Html.Partial("~/Views/GlobalTenders/Partial/partialSearchResultData.cshtml")
        </div>
    </div>
</div>