TenderAssist/Controllers/InquiryFormsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TenderAssist.CommonHelper;
using TenderAssist.Models;
using TenderAssist.Models.DBConnection;
using TenderAssist.ViewModel;
using static TenderAssist.CommonHelper.Utility;

namespace TenderAssist.Controllers
{
    public class InquiryFormsController : Controller
    {
        private readonly TenderInformation _tenderInfo;
        private readonly GetListItems _getListItems;
        private readonly CommonController _common;


        public InquiryFormsController()
        {
            _tenderInfo = new TenderInformation();
            _getListItems = new GetListItems();
            _common = new CommonController();
        }

        public ActionResult IndianTenders()
        {
            var tenderDetail = new TenderDetail
            {
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.IndianTender,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.IndianTender,
                FormType = FormType.OtherForms
            };

            return View("InquiryForm", tenderDetail);
        }
        public ActionResult GlobalTenders()
        {
            var tenderDetail = new TenderDetail
            {
                CountryList = _getListItems.CountryList(),
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.GlobalTender,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.GlobalTender,
                FormType = FormType.RegistrationForm
            };

            return View("InquiryForm", tenderDetail);
        }
        public ActionResult TenderResult()
        {
            var tenderDetail = new TenderDetail
            {
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.TenderResult,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.TenderResult,
                FormType = FormType.OtherForms
            };

            return View("InquiryForm", tenderDetail);
        }
        public ActionResult TenderAssist()
        {
            var tenderDetail = new TenderDetail
            {
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.TenderAssist,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.TenderAssist,
                FormType = FormType.OtherForms
            };

            return View("InquiryForm", tenderDetail);
        }
        public ActionResult result()
        {
            var tenderDetail = new TenderDetail
            {
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.result,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.Result,
                FormType = FormType.OtherForms
            };

            return View("InquiryForm", tenderDetail);
        }
        public ActionResult project()
        {
            var tenderDetail = new TenderDetail
            {
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.project,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.Project,
                FormType = FormType.OtherForms
            };

            return View("InquiryForm", tenderDetail);
        }
        public ActionResult VendorEmpanelment()
        {
            var tenderDetail = new TenderDetail
            {
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.VendorEmpanelment,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.VendorEmpanelment,
                FormType = FormType.OtherForms
            };

            return View("InquiryForm", tenderDetail);
        }
        public ActionResult Subcontracting()
        {
            var tenderDetail = new TenderDetail
            {
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.SubContractor,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.SubContractor,
                FormType = FormType.OtherForms
            };

            return View("InquiryForm", tenderDetail);
        }
        public ActionResult DigitalSignature()
        {
            var tenderDetail = new TenderDetail
            {
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.DigitalSignature,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.DigitalSignature,
                FormType = FormType.OtherForms
            };

            return View("InquiryForm", tenderDetail);
        }

        public ActionResult ISOConsultant()
        {
            var tenderDetail = new TenderDetail
            {
                StateList = _getListItems.StateList(),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.ISOConsultant,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.ISOConsultant,
                FormType = FormType.OtherForms
            };

            return View("InquiryForm", tenderDetail);
        }


        public ActionResult NewRegistration()
        {
            var tenderDetail = new TenderDetail
            {
                CountryList = _getListItems.CountryList(),
                StateList = _getListItems.StateList(0),
                CityList = _getListItems.CityList(0),
                Subscribetype = SubscribType.Registration,
                DownloadTenderRefNo = 0,
                FormTitle = SubscribTypeDisplsyText.Registration,
                FormType = FormType.RegistrationForm
            };

            return View("RegistrationForm", tenderDetail);
        }

        [HttpPost]
        public ActionResult SubmitInquiryDetail(FormCollection coll)
        {
            var msg = "ok";
            string userEmail;
            var inqForm = new tbInquiryRegForm();
            var inqFormUserId = 0;

            var ModuleType = 0;
            var InquiryTypeId = 0;
            var LinkId = 0;
            var BrowserLink = "";

            var tYear = "";
            var tenderId = 0;

            var encryptedOurRefNo = "";
            var encryptedtYear = "";
            var encryptedtUserId = "";
            var isDowloadDoc = false; var isExportExcelDoc = false;

            var DownloadDocumentUrl = "";

            var PopUpFormControlId = "";
            var InquiryTypeName = "";

            string adminFromId = ConfigurationManager.AppSettings["SMTP_EmailId"].ToString();

            var LoginUserId = Session["ClientID"] == null ? 0 : Convert.ToInt32(Session["ClientID"]);

            try
            {
                //var ClientIpAddress = RequestHelpers.GetClientIpAddress();

                var FormType = coll.Get("FormType").ToString().ToLower().Trim();
                InquiryTypeName = coll.Get("InquiryTypeName").ToString();
                var captchaHiddenId = "hdn_Captcha_Code";

                var captchaCode = coll.Get(captchaHiddenId);
                var txtCaptcha = coll.Get("txtCaptcha" + PopUpFormControlId);
                BrowserLink = coll.Get("BrowserLink").ToString();

                if (Convert.ToInt32(FormType) != Utility.FormType.PayOnline)
                {
                    if (captchaCode == null || (txtCaptcha.Trim() != captchaCode.ToString().Trim()))
                    {
                        msg = "captchaerror"; userEmail = "";
                        return Json(new { msg, userEmail, inqFormUserId }, JsonRequestBehavior.AllowGet);
                    }
                }

                InquiryRegFormFields RegFormParams = new InquiryRegFormFields()
                {
                    InquiryTypeID = Convert.ToInt32(coll.Get("InquiryTypeID")),
                    intClientPurpose = 1,
                    OurRefNo = Convert.ToInt32(coll.Get("TenderID")),
                    NewID = Convert.ToInt32(coll.Get("NewID")),
                    ModuleType = Convert.ToInt32(coll.Get("ModuleType")),

                    Name = coll.Get("txtName"),
                    MobNo = coll.Get("txtMobileNo"),
                    EmailID = coll.Get("txtEmailId"),
                    InterestedTenders = coll.Get("txtInterestedTenders"),
                    CompName = FormType != Utility.FormType.ContactForm.ToString() ? coll.Get("txtCompanyName") : "",

                    //Designation = !isContactForm ? coll.Get("txtDesignation") : "",

                    //Address = FormType == Utility.FormType.RegistrationForm.ToString() ? coll.Get("txtAddress") : "",
                    //PhoneNo = !isContactForm ? coll.Get("txtPhoneNo") : "",
                    //Website = !isContactForm ? coll.Get("txtWebsite") : "",

                    Country = FormType == Utility.FormType.RegistrationForm.ToString() ? Convert.ToInt32(coll.Get("drpCountry")) : 0,
                    State = Convert.ToInt32(coll.Get("drpState")),

TenderAssist/Views/Home/About.cshtml
<div class="container_fullMiddle">
    <div class="breadcrumbgrid">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                    <div class="CurrentDiv">
                        <a href="/" itemprop="url" style="text-decoration: none;">
                            <span itemprop="title">Home</span>
                        </a>
                    </div>
                    <div itemprop="child" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                        <div class="CurrentDiv">
                            <span class="seperator">›</span>
                        </div>
                        <div class="CurrentDiv">
                            <span itemprop="title" class="text-bold">About TenderAssist247</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-1">

        </div>
        <div class="col-md-10">
            <div id="categories">
                <h1 class="pagetitle">
                    About TenderAssist247
                </h1>
                <p class="pagedescription">
                    TenderAssist247 have more than 10 Years experience to help organisations bid for Government & Public Sector tenders.
                </p>
                <br />
                <h3 class="subtitle">
                    Our Mission Statement is:-
                </h3>
                <p class="pagedescription">
                    To provide a customized solution to improving client opportunities to bid for and win Government & Public Sector contracts. Using our core values of experience and professionalism, we will help to create and deliver quality bid responses with integrity, honesty and a strong sense of responsibility.
                </p>
                <p class="pagedescription">
                    TenderAssist247 has developed a strong portfolio of products which offer our clients a carefully constructed path through the Government & public sector tendering process.
                </p>
                <p class="pagedescription">
                    From the formal release of the Contract Notice to the ultimate reward of Contract Award, we will help you through each stage of the process: – Tender Preparation Review, Daily Monitoring and Pre-qualification through to Invitation to Tender and Presentation Interview.
                </p>
                <p class="pagedescription">
                    We TenderAssist247 understand that every client has unique qualities to offer a Government & public sector organisation and we will ensure that those qualities are brought to the forefront in both the written and verbal bid.
                </p>
            </div>
        </div>
        <div class="col-md-1">

        </div>
    </div> 

</div>
 

TenderAssist/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TenderAssist/Views/Home/FAQ.cshtml
<div class="container_fullMiddle">
    <div class="breadcrumbgrid">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                    <div class="CurrentDiv">
                        <a href="/" itemprop="url" style="text-decoration: none;">
                            <span itemprop="title">Home</span>
                        </a>
                    </div>
                    <div itemprop="child" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                        <div class="CurrentDiv">
                            <span class="seperator">›</span>
                        </div>
                        <div class="CurrentDiv">
                            <span itemprop="title" class="text-bold">FAQ - TenderAssist247</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-1">

        </div>
        <div class="col-md-10">
            <div id="categories">
                <h1 class="pagetitle">
                    Frequently asked questions
                </h1>
                <div>
                    <button class="accordion">No obligation discussion/meeting</button>
                    <div class="panel">
                        <p>TenderAssist247 will explain the Government and Public Sector tendering process and discuss how we can help you to bid for contracts.</p>
                    </div>
                    <button class="accordion">Tender preparation</button>
                    <div class="panel">
                        <p>We will assess your ‘business ready’ status and set up your Bid Library.</p>
                    </div>
                    <button class="accordion">Daily monitoring service</button>
                    <div class="panel">
                        <p>TenderAssist247 will source relevant tender opportunities and provide advice to help you make your initial bid decision.</p>
                    </div>
                    <button class="accordion">Accreditation</button>
                    <div class="panel">
                        <p>
                            TenderAssist247 can help you attain accreditation (e.g. Construction,Safe Contractor, Manufacturer,Service Provider Suppliers etc)

                            We can also advise on achieving Lowest Bid process.
                        </p>
                    </div>
                    <button class="accordion">Pre-qualification questionnaires/invitations to tender</button>
                    <div class="panel">
                        <p>
                            TenderAssist247 will complete and submit all required tender documentation
                            Alternatively, we can provide a “Tender Check” service on documents that you have already completed
                        </p>
                    </div>
                    <button class="accordion">Presentation interviews</button>
                    <div class="panel">
                        <p>
                            TenderAssist247 can help you to create and deliver succinct presentations

                            Alternatively, we can critique your prepared presentations prior to interview
                        </p>
                    </div>
                    <button class="accordion">Training</button>
                    <div class="panel">
                        <p>If you have your own in-house tendering capability, we can review your processes and provide guidance</p>
                    </div>
                    <button class="accordion">Procurement workshop</button>
                    <div class="panel">
                        <p>We produce bespoke Procurement Workshops to help businesses understand the Public Sector tendering process.</p>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-1">

        </div>
    </div>



</div>

<style>
    .accordion {
        background-color: #eee;
        color: #444;
        cursor: pointer;
        padding: 18px;
        width: 100%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 18px;
        transition: 0.4s;
    }

        .accordion.active, .accordion:hover {
            background-color: #ccc;
        }

        .accordion:after {
            content: '\002B';
            color: #777;
            font-weight: bold;
            float: right;
            margin-left: 5px;
        }

        .accordion.active:after {
            content: "\2212";
        }

    .panel {
        padding: 2px 18px;
        background-color: white;
        max-height: 0;
        overflow: hidden;
        transition: max-height 0.2s ease-out;
        margin-bottom: 0px !important;
        font-size: 15px;
    }
</style>
<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.maxHeight) {
                panel.style.maxHeight = null;
            } else {
                panel.style.maxHeight = panel.scrollHeight + "px";
            }
        });
    }
</script>

TenderAssist/Views/Home/Index.cshtml
@model TenderAssist.ViewModel.TenderDetail
@using TenderAssist.CommonHelper;

@Html.Partial("Sections/_HomeImageSlider")

<div class="container_fullMiddle">
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">
            @Html.Partial("Sections/_HomeSearchPanel")
        </div>
        <div class="col-md-2">

        </div>
    </div>
    <div id="loader" style="display:none;">
        @Html.Partial("partialSpinnerLoadingView")
    </div>
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("Sections/_HomeAdvertiesment")
        </div>
        <div class="col-md-10">
            <div class="well well-sm">
                @Html.Partial("Sections/_HomeMenuLinks")
                <div id="categories">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="section_panel">
                                <div id="displayPanel" class="display_panel">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="grayline"></div>   
    @Html.Partial("Sections/_HomeCategoryPanel")

</div>

<script>
    var loadDataList = '@Url.Action("GetHomeLinkData", "Home")';
    var loadTendersByList = '@Url.Action("GetTendersByType", "Home")';

    var StateId = parseInt('@Utility.TenderTypeList.State');
    var CityId = parseInt('@Utility.TenderTypeList.City');
    var IndustryId = parseInt('@Utility.TenderTypeList.Industry');
    var SubIndustryId = parseInt('@Utility.TenderTypeList.SubIndustry');
    var AgencyId = parseInt('@Utility.TenderTypeList.Agency');
    var SectorId = parseInt('@Utility.TenderTypeList.Sector');
    var OwnershipId = parseInt('@Utility.TenderTypeList.Ownership');
    var KeywordId = parseInt('@Utility.TenderTypeList.Keyword');

    var isHomePage = true;
</script>

@Scripts.Render("~/bundles/load-dataformenu-script")

TenderAssist/Views/Home/PaymentStatus.cshtml
@using System.Configuration
@using System.Globalization
@model TenderAssist.ViewModel.TenderDetail


<div class="container_fullMiddle">
    <div class="breadcrumbgrid">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb" itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb">
                    <div class="CurrentDiv">
                        <a href="/" itemprop="url" style="text-decoration: none;">
                            <span itemprop="title">Home</span>
                        </a>
                    </div>
                    <div itemprop="child" itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb">
                        <div class="CurrentDiv">
                            <span class="seperator">›</span>
                        </div>
                        <div class="CurrentDiv">
                            <span itemprop="title" class="text-bold">
                                Pay Online
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="well SuccessMessageHeaderSpan">
                <h3>Dear <b>@ViewBag.UserEmail, </b></h3>
                <br />
                <span>
                    Thank you for submitting the details.
                </span>
                <br />
                <br />
                <span>
                    @Html.Raw(Model.DisplayText)
                    
                </span> 
                <br /><br />
                <span>
                    Check your email <b>@ViewBag.EmailId </b>for further details.
                    <br />
                    You may also reach us on +91 97247 00247.
                </span>
                <br />
                <br />
                <a class="btn btn-success btn-flat btn-lg" href="@Url.Action("Index", "Payonline")">
                    <i class="fa fa-rupee"></i>
                    PayNow
                </a>
                <br />
                <br />
            </div>

        </div>
    </div>
</div>

<style>
    .SuccessMessageHeaderSpan {
        font-size: 15px;
    }
</style>

TenderAssist/Views/Home/UserLogin.cshtml
@model TenderAssist.ViewModel.TenderDetail

@Scripts.Render("~/bundles/user-login-script")

<div class="container_fullInner">
    <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-10 well">
            <div class="breadcrumbgrid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="breadcrumb" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                            <div class="CurrentDiv">
                                <a href="/" itemprop="url" style="text-decoration: none;">
                                    <span itemprop="title">Home</span>
                                </a>
                            </div>
                            <div itemprop="child" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                                <div class="CurrentDiv">
                                    <span class="seperator">›</span>
                                </div>
                                <div class="CurrentDiv">
                                    <span itemprop="title" class="text-bold">Login</span>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="padTB10">
                <div class="col-md-3">
                    <div class="box box-info">
                        <div class="box-header">
                            <span class="box-title">
                                <i class="fa fa-lock fa-2x icon text-centericon"></i>
                                TenderAssist - Login
                            </span>
                        </div>
                        <div class="grayline"></div>
                        <div class="box-body">
                            <div class="errMsg mar5" id="errmsg">
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user-md"></i></span>
                                    @Html.TextBoxFor(model => model.LoginUserDetails.strEmailId1, new { @class = "form-control textbox", @placeholder = "Your Email Id" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-key"></i></span>
                                    @Html.PasswordFor(model => model.LoginUserDetails.strPassword, new { @class = "form-control textbox", @placeholder = "Your Password" })
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="row mar5">
                                <div class="col-md-12">
                                    <button class="btn btn-info btn-lg btn-block" type="submit" id="btnLogin">
                                        <i class="fa fa-unlock-alt"></i>&nbsp; Login
                                    </button>
                                    <div id="divWait" style="display: none;">
                                        @Html.Partial("partialSpinnerLoadingView")
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <h2>
                        <span>New user ?</span>
                    </h2>
                    <a href="@Url.Action("NewRegistration", "InquiryForms")">
                        <i class="fa fa-edit"></i>
                        Click here to subscrib with us
                    </a>
                </div>
                <div class="col-md-9">
                    <div id="our-team">
                        <div class="subscribdetails">
                            <div class="row">
                                <div class="col-md-12 plan price-four wow fadeInLeft animated ">
                                    <br />
                                    <div class="text-center">
                                        <p>
                                            <b>TenderAssist247.com</b> is one of the leading tender portal with the Database of around more than 20,00,000 inquries in the form of <b>Tenders</b>, <b>Auctions</b>, <b>Projects and Contract awards</b> from Government, semi government and private players from every corner of the country who are looking for Vendors like you.<br />
                                            Every lead is as important for your business growth.
                                        </p>
                                        <h2 class="ourteamh2">
                                            TenderAssist247.com :: Service Details
                                        </h2>
                                        <p>
                                            <i class="fa fa-arrow-circle-right"></i>&nbsp;Daily tender alert for your category and requirement.<br />
                                            <i class="fa fa-arrow-circle-right"></i>&nbsp;Anytime access to tenders.<br />
                                            <i class="fa fa-arrow-circle-right"></i>&nbsp;Online tender Documents in one touch.<br />
                                            <i class="fa fa-arrow-circle-right"></i>&nbsp;Online support for any querries.<br />
                                            <i class="fa fa-arrow-circle-right"></i>&nbsp;Live updates for tender awarded.<br />
                                            <i class="fa fa-arrow-circle-right"></i>&nbsp;Apart for tenders information get private leads too.<br />
                                            <i class="fa fa-arrow-circle-right"></i>&nbsp;Online Tendering support.<br />
                                            <i class="fa fa-arrow-circle-right"></i>&nbsp;Bidding consultancy and many more.
                                        </p>
                                    </div>
                                </div>
                            </div>                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-1">
        </div>
    </div>
</div>